# Generated by Django 3.2.19 on 2024-05-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='main_skill',
        ),
    ]
