# Generated by Django 5.1.4 on 2025-01-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_certificate_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='title',
            new_name='issuing_company',
        ),
    ]
